[package]
name = "resolver-tests"
version = "0.0.0"
rust-version.workspace = true
edition.workspace = true
publish = false

[dependencies]
cargo.workspace = true
cargo-util.workspace = true
proptest.workspace = true
varisat.workspace = true
