[package]
name = "resolver-tests"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
cargo.workspace = true
cargo-util.workspace = true
is-terminal.workspace = true
lazy_static.workspace = true
proptest.workspace = true
varisat.workspace = true
