[package]
name = "cargo-credential-1password"
version = "0.4.1"
edition.workspace = true
license.workspace = true
rust-version = "1.70.0"  # MSRV:3
repository = "https://github.com/rust-lang/cargo"
description = "A Cargo credential process that stores tokens in a 1password vault."

[dependencies]
cargo-credential.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
