[package]
name = "cargo-test-macro"
version = "0.4.8"
edition.workspace = true
rust-version = "1.91"  # MSRV:1
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Helper proc-macro for Cargo's testsuite."

[lib]
proc-macro = true

[lints]
workspace = true
