language: rust
rust:
  - 1.2.0
  - stable
  - beta
  - nightly
sudo: false
script:
  - ./configure --prefix=$HOME/cargo-install --disable-cross-tests
  - make
  - make test
  - make distcheck
  - make doc
  - make install
  - make uninstall
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $(uname -s) = Linux ] &&
  pip install ghp-import --user $USER &&
  $HOME/.local/bin/ghp-import -n target/doc &&
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    - secure: scGpeetUfba5RWyuS4yt10bPoFAI9wpHEReIFqEx7eH5vr2Anajk6+70jW6GdrWVdUvdINiArlQ3An2DeB9vEUWcBjw8WvuPtOH0tDMoSsuVloPlFD8yn1Ac0Bx9getAO5ofxqtoNg+OV4MDVuGabEesqAOWqURNrBC7XK+ntC8=

os:
  - linux
  - osx

branches:
  only:
    - master

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - g++-multilib
      - lib32stdc++6
