dist: xenial
language: shell

git:
  depth: 1
  quiet: true

matrix:
  fast_finish: true
  include:
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu

    - os: osx
      osx_image: xcode9.2
      env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin

    - os: windows
      env: TARGET=x86_64-pc-windows-msvc
      services: nil

    - name: rustfmt
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check

before_install:
  - curl -sSL https://sh.rustup.rs | sh -s -- -y --default-toolchain=stable --profile=minimal
  - export PATH="$HOME/.cargo/bin:$PATH"

script:
  - cargo build
  - cargo test
