language: rust
rust: stable
sudo: required
dist: trusty

git:
  depth: 1

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
           ALT=i686-unknown-linux-gnu
      if: branch != master OR type = pull_request

    - env: TARGET=x86_64-apple-darwin
           ALT=i686-apple-darwin
      os: osx
      osx_image: xcode9.2
      if: branch != master OR type = pull_request

    - env: TARGET=x86_64-unknown-linux-gnu
           ALT=i686-unknown-linux-gnu
      rust: beta
      if: branch != master OR type = pull_request

    # Minimum Rust supported channel. We enable these to make sure we
    # continue to work on the advertised minimum Rust version.
    # However cargo only supports the latest stable so this will get
    # increased every 6 weeks or so when the first PR to use a new feature.
    - env: TARGET=x86_64-unknown-linux-gnu
           ALT=i686-unknown-linux-gnu
      rust: 1.32.0
      script:
        - rustup toolchain install nightly || travis_terminate 1
        - cargo +nightly generate-lockfile -Z minimal-versions || travis_terminate 1
        - cargo -V || travis_terminate 1
        - cargo test --features=deny-warnings || travis_terminate 1
      if: branch != master OR type = pull_request

    - env: TARGET=x86_64-unknown-linux-gnu
           ALT=i686-unknown-linux-gnu
      rust: nightly
      install:
        - travis_retry curl -Lf https://github.com/rust-lang-nursery/mdBook/releases/download/v0.1.7/mdbook-v0.1.7-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=$HOME/.cargo/bin
      script:
        - cargo test --features=deny-warnings || travis_terminate 1
        - cargo doc --no-deps || travis_terminate 1
        - (cd src/doc && mdbook build --dest-dir ../../target/doc) || travis_terminate 1
      if: branch != master OR type = pull_request

  exclude:
    - rust: stable

before_script:
  - rustup target add $ALT
script:
  - cargo test --features=deny-warnings

notifications:
  email:
    on_success: never

addons:
  apt:
    packages:
      - gcc-multilib
