environment:
  CFG_DISABLE_CROSS_TESTS: 1
  matrix:
  - MSVC: 1
    BITS: 32
    TARGET: i686-pc-windows-msvc
    ARCH: x86
    NEEDS_LIBGCC: 1
  - MSVC: 1
    BITS: 64
    TARGET: x86_64-pc-windows-msvc
    ARCH: amd64

install:
  - python src/etc/install-deps.py
  - python src/etc/dl-snapshot.py %TARGET%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %ARCH%
  - SET PATH=%PATH%;%cd%/rustc/bin
  - SET PATH=%PATH%;%cd%/target/snapshot/cargo/bin
  - if defined NEEDS_LIBGCC set PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test
