[package]
name = "build-rs"
version = "0.2.0"
edition = "2021"
rust-version = "1.76"
publish = false

[dependencies]
unicode-ident = "1.0.13"

[features]

## Experimental API. This feature flag is **NOT** semver stable.
unstable = []

[workspace]
members = ["test-lib"]
