[project]
name = "cargo"
version = "0.12.0"
authors = ["Yehuda Katz <wycats@gmail.com>",
           "Carl Lerche <me@carllerche.com>",
           "Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
homepage = "https://crates.io"
repository = "https://github.com/rust-lang/cargo"
documentation = "http://doc.crates.io/cargo"
description = """
Cargo, a package manager for Rust.
"""

[lib]
name = "cargo"
path = "src/cargo/lib.rs"

[dependencies]
advapi32-sys = "0.1"
crates-io = { path = "src/crates-io", version = "0.4" }
crossbeam = "0.2"
curl = "0.2"
curl-sys = "0.1"
docopt = "0.6"
env_logger = "0.3"
filetime = "0.1"
flate2 = "0.2"
fs2 = "0.2"
git2 = "0.4"
git2-curl = "0.4"
glob = "0.2"
kernel32-sys = "0.2"
libc = "0.2"
libgit2-sys = "0.4"
log = "0.3"
num_cpus = "0.2"
regex = "0.1"
rustc-serialize = "0.3"
semver = "0.2.2"
tar = "0.4"
tempdir = "0.3"
term = "0.4.4"
toml = "0.1"
url = "1.1"
winapi = "0.2"

[dev-dependencies]
hamcrest = "0.1"
bufstream = "0.1"
filetime = "0.1"
cargotest = { path = "tests/cargotest" }

[[bin]]
name = "cargo"
test = false
doc = false
