[package]
name = "cargo"
version = "0.13.0"
authors = ["Yehuda Katz <wycats@gmail.com>",
           "Carl Lerche <me@carllerche.com>",
           "Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
homepage = "https://crates.io"
repository = "https://github.com/rust-lang/cargo"
documentation = "http://doc.crates.io/cargo"
description = """
Cargo, a package manager for Rust.
"""

[lib]
name = "cargo"
path = "src/cargo/lib.rs"

[dependencies]
advapi32-sys = "0.2"
crates-io = { path = "src/crates-io", version = "0.4" }
crossbeam = "0.2"
curl = "0.3"
docopt = "0.6"
env_logger = "0.3"
filetime = "0.1"
flate2 = "0.2"
fs2 = "0.2"
git2 = "0.4"
libgit2-sys = "0.4"
git2-curl = "0.5"
glob = "0.2"
kernel32-sys = "0.2"
libc = "0.2"
log = "0.3"
miow = "0.1"
num_cpus = "1.0"
regex = "0.1"
rustc-serialize = "0.3"
semver = "0.2.3"
tar = { version = "0.4", default-features = false }
tempdir = "0.3"
term = "0.4.4"
toml = "0.2"
url = "1.1"
winapi = "0.2"

[target.'cfg(unix)'.dependencies]
openssl = "0.7"

[dev-dependencies]
hamcrest = "0.1"
bufstream = "0.1"
filetime = "0.1"
cargotest = { path = "tests/cargotest" }

[[bin]]
name = "cargo"
test = false
doc = false
