[project]
name = "cargo"
version = "0.1.0"
authors = ["Yehuda Katz <wycats@gmail.com>",
           "Carl Lerche <me@carllerche.com>",
           "Alex Crichton <alex@alexcrichton.com>"]

[lib]
name = "cargo"
path = "src/cargo/lib.rs"

[dependencies]
toml = "0.1"
semver = "0.1"
curl = "0.1"
tar = "0.1"
flate2 = "0.1"
git2 = "0.1"
glob = "0.1"
time = "0.1"
log = "0.1"
docopt = "0.6"
url = "0.2"
rustc-serialize = "0.2"
term = "0.1"

[dev-dependencies.hamcrest]
git = "https://github.com/carllerche/hamcrest-rust.git"

[dependencies.registry]
path = "src/registry"

[[bin]]
name = "cargo"
test = false
doc = false

[[test]]
name = "tests"
[[bench]]
name = "tests"
path = "tests/tests.rs"

[[test]]
name = "resolve"
