[project]
name = "cargo"
version = "0.9.0"
authors = ["Yehuda Katz <wycats@gmail.com>",
           "Carl Lerche <me@carllerche.com>",
           "Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
homepage = "https://crates.io"
repository = "https://github.com/rust-lang/cargo"
documentation = "http://doc.crates.io"
description = """
Cargo, a package manager for Rust.
"""

[lib]
name = "cargo"
path = "src/cargo/lib.rs"

[dependencies]
advapi32-sys = "0.1"
crates-io = { path = "src/crates-io", version = "0.1" }
crossbeam = "0.2"
curl = "0.2"
docopt = "0.6"
env_logger = "0.3"
filetime = "0.1"
flate2 = "0.2"
git2 = "0.3"
git2-curl = "0.3"
glob = "0.2"
kernel32-sys = "0.2"
libc = "0.2"
libgit2-sys = "0.3"
log = "0.3"
num_cpus = "0.2"
regex = "0.1"
rustc-serialize = "0.3"
semver = "0.2.0"
tar = "0.4"
term = "0.4.4"
time = "0.1"
toml = "0.1"
url = "0.2"
winapi = "0.2"

[dev-dependencies]
tempdir = "0.3"
hamcrest = "0.1"
bufstream = "0.1"
filetime = "0.1"

[[bin]]
name = "cargo"
test = false
doc = false

[[test]]
name = "tests"

[[test]]
name = "resolve"
