[package]
name = "home"
version = "0.1.0"
authors = [ "Brian Anderson <andersrb@gmail.com>" ]
description = "Shared definitions of home directories"
documentation = "https://docs.rs/home"
repository = "https://github.com/brson/home"
license = "MIT/Apache-2.0"

[target."cfg(windows)".dependencies]
scopeguard = "0.1.2"
winapi = "0.2.8"
kernel32-sys = "0.2.1"
advapi32-sys = "0.2.0"
userenv-sys = "0.2.0"

