[package]
name = "cargo"
version = "0.26.0"
authors = ["Yehuda Katz <wycats@gmail.com>",
           "Carl Lerche <me@carllerche.com>",
           "Alex Crichton <alex@alexcrichton.com>"]
license = "MIT OR Apache-2.0"
homepage = "https://crates.io"
repository = "https://github.com/rust-lang/cargo"
documentation = "https://docs.rs/cargo"
description = """
Cargo, a package manager for Rust.
"""

[lib]
name = "cargo"
path = "src/cargo/lib.rs"

[dependencies]
atty = "0.2"
crates-io = { path = "src/crates-io", version = "0.15" }
crossbeam = "0.3"
crypto-hash = "0.3"
curl = "0.4.6"
docopt = "0.8.1"
env_logger = "0.5"
failure = "0.1.1"
filetime = "0.1"
flate2 = "1.0"
fs2 = "0.4"
git2 = "0.6.11"
git2-curl = "0.7"
glob = "0.2"
hex = "0.3"
home = "0.3"
ignore = "0.3"
jobserver = "0.1.6"
libc = "0.2"
libgit2-sys = "0.6"
log = "0.4"
num_cpus = "1.0"
same-file = "1"
scoped-tls = "0.1"
semver = { version = "0.9.0", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_ignored = "0.0.4"
serde_json = "1.0"
shell-escape = "0.1"
tar = { version = "0.4", default-features = false }
tempdir = "0.3"
termcolor = "0.3"
toml = "0.4"
url = "1.1"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = { version = "0.4.4", features = ["mac_os_10_7_support"] }

[target.'cfg(windows)'.dependencies]
miow = "0.2"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = [
  "handleapi",
  "jobapi",
  "jobapi2",
  "minwindef",
  "ntdef",
  "processenv",
  "processthreadsapi",
  "psapi",
  "synchapi",
  "winerror",
  "winbase",
  "wincon",
  "winnt",
]

[dev-dependencies]
bufstream = "0.1"
cargotest = { path = "tests/cargotest", version = "0.1" }
filetime = "0.1"
hamcrest = "=0.1.1"

[[bin]]
name = "cargo"
test = false
doc = false
