[package]
authors = [
    "Pascal Hertleif <killercup@gmail.com>",
    "Oliver Schneider <oli-obk@users.noreply.github.com>",
]
license = "Apache-2.0/MIT"
name = "rustfix"
description = "Automatically apply the suggestions made by rustc"
repository = "https://github.com/rust-lang-nursery/rustfix"
documentation = "https://docs.rs/rustfix"
edition = "2018"
readme = "Readme.md"
version = "0.4.4"
exclude = [
    "etc/*",
    "examples/*",
    "tests/*",
]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
failure = "0.1.2"
log = "0.4.1"

[dev-dependencies]
duct = "0.9"
env_logger = "0.5.0-rc.1"
log = "0.4.1"
tempdir = "0.3.5"
proptest = "0.7.0"
difference = "2.0.0"

[workspace]
