[package]
name = "cargo-credential-libsecret"
version = "0.4.1"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository = "https://github.com/rust-lang/cargo"
description = "A Cargo credential process that stores tokens with GNOME libsecret."

[dependencies]
anyhow.workspace = true
cargo-credential.workspace = true
libloading.workspace = true
