[package]
name = "mdman"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Creates a man page page from markdown."

[dependencies]
anyhow = "1.0.31"
handlebars = { version = "3.2.1", features = ["dir_source"] }
pulldown-cmark = { version = "0.7.2", default-features = false }
same-file = "1.0.6"
serde_json = "1.0.56"
url = "2.2.2"

[dev-dependencies]
pretty_assertions = "0.6.1"
