[package]
name = "xtask-spellcheck"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
cargo_metadata.workspace = true
cargo-util.workspace = true
clap.workspace = true
semver.workspace = true

[lints]
workspace = true
