[package]
name = "cargo-credential-macos-keychain"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/cargo"
description = "A Cargo credential process that stores tokens in a macOS keychain."

[dependencies]
cargo-credential = { version = "0.1.0", path = "../cargo-credential" }
security-framework = "2.0.0"
