[book]
title = "The Cargo Book"
authors = ["Alex Crichton", "Steve Klabnik", "Carol Nichols", "with contributions from the Rust community"]

[output.html]
additional-css = ["theme/cargo.css"]
smart-punctuation = true # Enable smart-punctuation feature for more than quotes.
git-repository-url = "https://github.com/rust-lang/cargo/tree/master/src/doc/src"
edit-url-template = "https://github.com/rust-lang/cargo/edit/master/src/doc/{path}"

[output.html.search]
use-boolean-and = true

[output.html.search.chapter]
"CHANGELOG.md" = { enable = false }

[output.html.redirect]
"/commands/cargo-git-checkout.html" = "./deprecated-and-removed.html"
"/commands/cargo-read-manifest.html" = "./deprecated-and-removed.html"
"/commands/cargo-verify-project.html" = "./deprecated-and-removed.html"
"/guide/build-cache.html" = "../reference/build-cache.html"
"/reference/manifest.html#building-dynamic-or-static-libraries" = "cargo-targets.html#the-crate-type-field"
"/reference/manifest.html#configuring-a-target" = "cargo-targets.html#configuring-a-target"
"/reference/manifest.html#examples" = "cargo-targets.html#examples"
"/reference/manifest.html#integration-tests" = "cargo-targets.html#integration-tests"
"/reference/manifest.html#package-build" = "manifest.html#the-build-field"
"/reference/manifest.html#package-metadata" = "manifest.html#the-package-section"
"/reference/manifest.html#package-selection" = "workspaces.html#package-selection"
"/reference/manifest.html#rules" = "features.html"
"/reference/manifest.html#rust-version" = "rust-version.html"
"/reference/manifest.html#target-auto-discovery" = "cargo-targets.html#target-auto-discovery"
"/reference/manifest.html#tests" = "cargo-targets.html#tests"
"/reference/manifest.html#the-authors-field-optional" = "manifest.html#the-authors-field"
"/reference/manifest.html#the-build-field-optional" = "manifest.html#the-build-field"
"/reference/manifest.html#the-documentation-field-optional" = "manifest.html#the-documentation-field"
"/reference/manifest.html#the-edition-field-optional" = "manifest.html#the-edition-field"
"/reference/manifest.html#the-exclude-and-include-fields-optional" = "manifest.html#the-exclude-and-include-fields"
"/reference/manifest.html#the-features-section" = "features.html#the-features-section"
"/reference/manifest.html#the-links-field-optional" = "manifest.html#the-links-field"
"/reference/manifest.html#the-metadata-table-optional" = "manifest.html#the-metadata-table"
"/reference/manifest.html#the-patch-section" = "overriding-dependencies.html#the-patch-section"
"/reference/manifest.html#the-project-layout" = "../guide/project-layout.html"
"/reference/manifest.html#the-publish--field-optional" = "manifest.html#the-publish-field"
"/reference/manifest.html#the-replace-section" = "overriding-dependencies.html#the-replace-section"
"/reference/manifest.html#the-required-features-field-optional" = "cargo-targets.html#the-required-features-field"
"/reference/manifest.html#the-workspace--field-optional" = "manifest.html#the-workspace-field"
"/reference/manifest.html#the-workspace-section" = "workspaces.html#the-workspace-section"
"/reference/manifest.html#usage-in-end-products" = "features.html"
"/reference/manifest.html#usage-in-packages" = "features.html"
"/reference/manifest.html#using-patch-with-multiple-versions" = "overriding-dependencies.html#using-patch-with-multiple-versions"
"/reference/manifest.html#virtual-workspace" = "workspaces.html"
"/reference/registries.html#index-format" = "registry-index.html"
"/reference/registries.html#login" = "registry-web-api.html#login"
"/reference/registries.html#owners" = "registry-web-api.html#owners"
"/reference/registries.html#owners-add" = "registry-web-api.html#owners-add"
"/reference/registries.html#owners-list" = "registry-web-api.html#owners-list"
"/reference/registries.html#owners-remove" = "registry-web-api.html#owners-remove"
"/reference/registries.html#publish" = "registry-web-api.html#publish"
"/reference/registries.html#running-a-registry" = "running-a-registry.html"
"/reference/registries.html#search" = "registry-web-api.html#search"
"/reference/registries.html#unyank" = "registry-web-api.html#unyank"
"/reference/registries.html#web-api" = "registry-web-api.html"
"/reference/registries.html#yank" = "registry-web-api.html#yank"
"/reference/resolver.html#other-constraints" = "#constraints-and-heuristics"
"/reference/resolver.html#pre-releases" = "specifying-dependencies.html#pre-releases"
"/reference/resolver.html#version-metadata" = "specifying-dependencies.html#version-metadata"
"/reference/specifying-dependencies.html#overriding-dependencies" = "overriding-dependencies.html"
"/reference/specifying-dependencies.html#overriding-repository-url" = "overriding-dependencies.html#overriding-repository-url"
"/reference/specifying-dependencies.html#overriding-with-local-dependencies" = "overriding-dependencies.html#paths-overrides"
"/reference/specifying-dependencies.html#prepublishing-a-breaking-change" = "overriding-dependencies.html#prepublishing-a-breaking-change"
"/reference/specifying-dependencies.html#testing-a-bugfix" = "overriding-dependencies.html#testing-a-bugfix"
"/reference/specifying-dependencies.html#working-with-an-unpublished-minor-version" = "overriding-dependencies.html#working-with-an-unpublished-minor-version"
"/reference/workspaces.html#virtual-manifest" = "workspaces.html#virtual-workspace"
