[package]
name = "build-rs-test-lib"
version = "0.2.0"
edition = "2021"
rust-version = "1.76"
publish = false

[features]
unstable = ["build-rs/unstable"]

[build-dependencies]
build-rs = { path = ".." }
