[package]
name = "semver-check"
authors = ["Eric Huss"]
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile.workspace = true

[lints]
workspace = true
