[package]
name = "semver-check"
version = "0.0.0"
authors = ["Eric Huss"]
rust-version.workspace = true
edition.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile.workspace = true
